FROM almalinux:8
# FROM centos:centos7
MAINTAINER sunny5156 <sunny5156@qq.com>

ENV HOME /vue-msf
ENV SRC_DIR $HOME/src
RUN mkdir -p ${SRC_DIR}

RUN cd ${SRC_DIR} \ 
	&& yum install -y git \
    && git clone --depth 1 -b v1.34.x https://github.com/grpc/grpc.git ./grpc \
	&& cd /vue-msf/src/grpc \
    && git submodule update --init --recursive 


RUN yum install -y  \
	automake autoconf \
	openssl openssl-devel \
	cmake make  gcc gcc-c++ kernel-devel  libtool pkg-config  diffutils




# -----------------------------------------------------------------------------
# Install grpc 
# ----------------------------------------------------------------------------- 
ENV GRPCVERSION 1.34.2
RUN cd ${SRC_DIR} \ 
    # && git clone --depth 1 -b v1.34.x https://github.com/grpc/grpc.git ./grpc \
    # && wget -q -O grpc-${GRPCVERSION}.tar.gz  https://github.com/grpc/grpc/archive/refs/tags/v${GRPCVERSION}.tar.gz \
    # && tar -zxf grpc-${GRPCVERSION}.tar.gz \
    # && cd grpc-${GRPCVERSION}\
	&& mkdir -p /vue-msf/local/ \
    && cd /vue-msf/src/grpc \
    # && git submodule update --init --recursive \
    && cd third_party/protobuf \
    && ./autogen.sh -fPIC \
    && ./configure "CFLAGS=-fPIC" "CXXFLAGS=-fPIC" --prefix=/vue-msf/local/ \
    && make  \
    && make install  \
    && ldconfig 

RUN cd /vue-msf/src/grpc \
    # && git submodule update --init --recursive \
    && mkdir -p cmake/build \
    && cd cmake/build \
    # && cmake ../.. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DCMAKE_INSTALL_PREFIX=/vue-msf/local/ \
    # && cmake ../.. -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package  -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/vue-msf/local/ \
    && cmake ../.. -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/vue-msf/local/ \
    && make \
    && make install \
    && ldconfig 

    

EXPOSE 22 80 443 8080 8000
# ENTRYPOINT ["/run.sh"]