; php options
include_path = ".:/vue-msf/hhvm/lib64/hhvm/"

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
hhvm.dynamic_extensions[mongodb] = /vue-msf/hhvm/lib64/hhvm/extensions/20150212/mongodb.so
hhvm.dynamic_extensions[mongo] = /vue-msf/hhvm/lib64/hhvm/extensions/20150212/mongo.so