hhvm.server.port = 9000
; hhvm.server.file_socket = /vue-msf/hhvm/run/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.source_root=/var/www
hhvm.server.upload.upload_max_file_size = 25M
; 线程数
hhvm.server.thread_count = 8
hhvm.server.max_requests = 5000
hhvm.server.request_memory_max_bytes = 2147483648

; 管理服务器
hhvm.admin_server.enabled = true
hhvm.admin_server.thread_count = 4
hhvm.admin_server.timeout = 60

hhvm.admin_server.port = 9009
hhvm.admin_server.ip = 127.0.0.1
hhvm.admin_server.password = 123456

; 允许的管理命令（根据需要设置）
hhvm.admin_server.commands[] = jit-stats
hhvm.admin_server.commands[] = stats
hhvm.admin_server.commands[] = perf-counters