hhvm.server.port = 9000
# hhvm.server.file_socket = /var/run/hhvm/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.source_root=/var/www
hhvm.server.upload.upload_max_file_size = 25M

memory_limit = 2G
hhvm.server.request_memory_max_bytes = 2147483648

; 在 server.ini 中调整 JIT 设置
hhvm.jit = true
;hhvm.jit_a_size = 2013265920
;hhvm.jit_a_cold_size = 402653184
;hhvm.jit_a_frozen_size = 67108864
;hhvm.jit_a_prof_size = 67108864
;hhvm.jit_max_translation_size = 16777216

; 在 server.ini 中调整 JIT 区域大小
; 减少 ASize (主代码区域)
hhvm.jit_a_size = 1073741824  ; 1 GiB

; 减少 AColdSize (冷代码区域)
hhvm.jit_a_cold_size = 268435456  ; 256 MiB

; 减少 AFrozenSize (冻结代码区域)
hhvm.jit_a_frozen_size = 134217728  ; 128 MiB

; 减少 GlobalDataSize (全局数据区域)
hhvm.jit_global_data_size = 67108864  ; 64 MiB



;hhvm.log.use_log_file = false
;hhvm.log.use_syslog = true

hhvm.log.level = Debug
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.native_stack_trace = true
hhvm.log.max_messages_per_request = 1000

;hhvm.log.level = Info
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.log.access.file = /var/log/hhvm/access.log
hhvm.log.header = true
;hhvm.log.native_stack_trace = true

;hhvm.log.file = /var/log/hhvm/error.log
;hhvm.log.access.file = /var/log/hhvm/access.log

;hhvm.repo.authoritative = true
hhvm.repo.authoritative = false
hhvm.repo.central.path = /var/cache/hhvm/hhvm.hhbc

hhvm.server.thread_count = 8
hhvm.server.max_requests = 5000

hhvm.admin_server.enabled = true
hhvm.admin_server.port = 9009
hhvm.admin_server.ip = 127.0.0.1
;hhvm.admin_server.password = 123456

; 允许的管理命令（根据需要设置）
hhvm.admin_server.commands[] = jit-stats
hhvm.admin_server.commands[] = stats
hhvm.admin_server.commands[] = perf-counters