hhvm.server.port = 9000
; hhvm.server.file_socket = /vue-msf/hhvm/run/hhvm.sock
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.source_root=/var/www
hhvm.server.upload.upload_max_file_size = 25M
; 线程数
hhvm.server.thread_count = 8
hhvm.server.max_requests = 5000
hhvm.server.request_memory_max_bytes = 2147483648

; 在 server.ini 中调整 JIT 设置
hhvm.jit = true
;hhvm.jit_a_prof_size = 67108864
;hhvm.jit_max_translation_size = 16777216
; 在 server.ini 中调整 JIT 区域大小
; 减少 ASize (主代码区域)
hhvm.jit_a_size = 1073741824  ; 1 GiB
; 减少 AColdSize (冷代码区域)
hhvm.jit_a_cold_size = 268435456  ; 256 MiB
; 减少 AFrozenSize (冻结代码区域)
hhvm.jit_a_frozen_size = 134217728  ; 128 MiB
; 减少 GlobalDataSize (全局数据区域)
hhvm.jit_global_data_size = 67108864  ; 64 MiB

;hhvm.repo.authoritative = true
hhvm.repo.authoritative = false
hhvm.repo.central.path = /vue-msf/data/hhvm/cache/hhvm.hhbc

; 管理服务器
hhvm.admin_server.enabled = true
hhvm.admin_server.thread_count = 4
hhvm.admin_server.timeout = 60

hhvm.admin_server.port = 9009
hhvm.admin_server.ip = 127.0.0.1
hhvm.admin_server.password = 123456

; 允许的管理命令（根据需要设置）
hhvm.admin_server.commands[] = jit-stats
hhvm.admin_server.commands[] = stats
hhvm.admin_server.commands[] = perf-counters