[program:hhvm]
command=/vue-msf/hhvm/bin/hhvm --config /vue-msf/hhvm/etc/config.hdf  --config /vue-msf/hhvm/etc/php.ini --config /vue-msf/hhvm/etc/server.ini --mode server
process_name=hhvm
numprocs=1
directory=/vue-msf/hhvm/
umask=022
priority=999
autostart=true
autorestart=true
startsecs=10
startretries=2
exitcodes=0,2
stopsignal=TERM
stopwaitsecs=10
user=super
redirect_stderr=true
stderr_logfile=NONE
redirect_stdout=true
stdout_logfile=NONE
