server {
        listen       80;
        server_name  localhost;
        root /vue-msf/data/www;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            index  index.html index.php index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location ~* \.(xml|ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)\$ {
            expires max;
            add_header Pragma "public";
            add_header Cache-Control "public, must-revalidate, proxy-revalidate";
            access_log off;
        }

        location ~ \.(hh|php)$ {
            fastcgi_keep_conn on;
            fastcgi_pass   127.0.0.1:9000;
            # fastcgi_pass   unix:/var/run/hhvm/hhvm.sock;
            fastcgi_buffers 16 16k; 
            fastcgi_buffer_size 32k;
            keepalive_requests 1024;
            keepalive_timeout 30s;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

    }